name: CI

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  # https://github.com/pytest-dev/pytest/issues/2042#issuecomment-429289164
  PY_IGNORE_IMPORTMISMATCH: 1

jobs:
  pytest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        deps:
          - label: Latest
            spec: >-
              gdal
          - label: Minimum
            spec: >-
              python=3.9
              gdal=3.5

      fail-fast: false
    name: ${{ matrix.os }} • ${{ matrix.deps.label }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yaml
          environment-name: s1-reader-env
          generate-run-shell: false
          create-args: ${{ matrix.deps.spec }}
          condarc: |
            channels:
              - conda-forge
      - name: Install
        run: |
          python -m pip install .
      - name: Test
        run: |
          python -m pip install pytest-recording
          python -m pytest -n0
